[package]
name = "addtopath"
version = "0.1.0"
edition = "2024"

[dependencies]
winreg = "0.52"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1" # Check if running as administrator
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell", # Correct feature for ShellExecuteExW
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_SystemInformation",
    "Win32_System_Environment", # For GetCommandLineW
    "Win32_System_Registry", # Added: Required by SHELLEXECUTEINFOW
]}

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
